import React, { Component } from "react";
import Footer from "../Common/Footer";
import Link from "next/link"
import "./CategoryList.css";
import Nav from "../Common/Nav/Nav";
import Finding from "./../Finding";
import Tickets from "./../Tickets";
import Logo1 from "../../assets/img/logo-social.png";
import Logo2 from "../../assets/img/logo-social1.png";

export default class CategoryList extends Component {
  render() {
    let u_data = this.props.user_data
    let authenticated = this.props.authenticated
    let url = "//www.sic.gov.co";

    let urlBanner = "//kiero.co/images/resources/deportes%20y%20fitness/1.jpg";

    var complete = {
      "deporte y fitness": {
        "estucture":[1, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3],
        "links": ["","//kiero.co/categoria/Gafas%20de%20Sol",
          "//kiero.co/categoria/Ropa%20deportiva",
          "//kiero.co/categoria/Rugby",
          "//kiero.co/categoria/Tenis%20y%20raquetas",
          "//kiero.co/categoria/Yoga",
          "//kiero.co/categoria/Suministros%20y%20equipo%20médico",
          "//kiero.co/categoria/Snowboard",
          "//kiero.co/categoria/Voleibol",
          "//kiero.co/categoria/Airsoft%20y%20Paintball",
          "//kiero.co/categoria/Fútbol",
          "//kiero.co/categoria/Artes%20Marciales",
          "//kiero.co/categoria/Béisbol%20y%20softball",
          "//kiero.co/categoria/Bocce",
          "//kiero.co/categoria/Ciclismo",
          "//kiero.co/categoria/Camping",
          "//kiero.co/categoria/Buceo%20y%20snorkel",
          "//kiero.co/categoria/Canotaje",
          "//kiero.co/categoria/Cricket",
          "//kiero.co/categoria/Correr",
          "//kiero.co/categoria/Natación",
          "//kiero.co/categoria/Deportes%20ecuestres",
          "//kiero.co/categoria/Navegación",
          "//kiero.co/categoria/Nutrición%20deportiva",
          "//kiero.co/categoria/Canotaje",
          "//kiero.co/categoria/Entrenamiento%20cardiovascular%20y%20de%20fuerza",
          "//kiero.co/categoria/Hockey",
          "//kiero.co/categoria/Juegos%20al%20aire%20libre",
          "//kiero.co/categoria/Juegos%20de%20lanzamiento",
          "//kiero.co/categoria/Accesorios%20deportivos",
          "//kiero.co/categoria/Escalada",
          "//kiero.co/categoria/Equipo%20de%20casino",
          "//kiero.co/categoria/Esgrima",
          "//kiero.co/categoria/Fan%20Shop",
          "//kiero.co/categoria/Gimnasia",
          "//kiero.co/categoria/Golf",
          "//kiero.co/categoria/Arcade%20y%20juegos%20de%20mesa",
          "//kiero.co/categoria/Baile",
          "//kiero.co/categoria/Bebidas%20en%20botella",
          "//kiero.co/categoria/Baloncesto",
          "//kiero.co/categoria/Boxeo",
          "//kiero.co/categoria/Bolos",
          "//kiero.co/categoria/Brújulas%20y%20odómetros",
          "//kiero.co/categoria/Danza",
          "//kiero.co/categoria/Juegos%20de%20sala",
          "//kiero.co/categoria/Caza%20y%20pesca",
          "//kiero.co/categoria/Esquí",
          "//kiero.co/categoria/Ropa%20al%20aire%20libre",
          "//kiero.co/categoria/Waterpolo",
          "//kiero.co/categoria/Surf",
          "//kiero.co/categoria/Billar",
          "//kiero.co/categoria/Dardos",
          "//kiero.co/categoria/Entrenadoresy%20árbitros",
          "//kiero.co/categoria/Lacrosse",
          "//kiero.co/categoria/Lucha%20deportiva",
          "//kiero.co/categoria/Medicina%20deportiva",
          "//kiero.co/categoria/Tienda%20para%20fanáticos",
          "//kiero.co/categoria/Equipo%20de%20campo,%20cancha%20y%20pista",
          "//kiero.co/categoria/Salud%20y%20bienestar"],
        "image_path":"//kiero.co/images/resources/deportes%20y%20fitness/","enable":[true]},
      "animales y mascotas": {"estructure":[1, 3, 2, 3, 1],
        "links": ["","//kiero.co/categoria/Comida20%para20%animales20%",
          "//kiero.co/categoria/Estetica20%y20%cuidado20%para20%animales20%",
          "//kiero.co/categoria/Aves",
          "//kiero.co/categoria/Roedores",
          "//kiero.co/categoria/Gatos",
          "//kiero.co/categoria/Reptiles20%y20%anfibios",
          "//kiero.co/categoria/Caballos",
          "//kiero.co/categoria/Peces",
          "//kiero.co/categoria/Perros"], 
        "image_path": "//kiero.co/images/resources/animales20%y20%mascotas/","enable": [true]},
      "bebes": {"estructure":[1, 2, 3, 2, 3, 2, 1],
        "links": ["","//kiero.co/categoria/Ropa%20para%20Bebés",
          "//kiero.co/categoria/Caminadores%20y%20Correpasillos",
          "//kiero.co/categoria/Cuarto%20del%20Bebé",
          "//kiero.co/categoria/Higiene20%y20%cuidado20%del20%bebé",
          "//kiero.co/categoria/Lactancia%20y%20Alimentación",
          "//kiero.co/categoria/Entretenimiento%20para%20Bebés",
          "//kiero.co/categoria/Paseo%20del%20Bebé",
          "//kiero.co/categoria/Salud20%del20%bebé20%",
          "//kiero.co/categoria/Seguridad20%para20%bebés",
          "//kiero.co/categoria/Artículos20%de20%maternidad",
          "//kiero.co/categoria/Corrales20%para20%bebés",
          "//kiero.co/categoria/Chupetes20%y20%mordedores",
          "//kiero.co/categoria/Art%C3%ADculos%20para%20Beb%C3%A9s"], 
        "image_path": "//kiero.co/images/resources/bebes/","enable": [true]},
      "belleza y cuidado personal": {"estructure":[1, 2, 3, 2, 3, 2],
        "links": ["","//kiero.co/categoria/electrodomesticos%20de%20belleza",
          "//kiero.co/categoria/extensiones20%y20%pelucas",
          "//kiero.co/categoria/higiene20%personal",
          "//kiero.co/categoria/Articulos20%de20%peluqueria",
          "//kiero.co/categoria/cuidado20%del20%cuerpo",
          "//kiero.co/categoria/maquillaje",
          "//kiero.co/categoria/depilación",
          "//kiero.co/categoria/perfumes%20y%20fragancias",
          "//kiero.co/categoria/cuidado%20del%20cabello",
          "//kiero.co/categoria/cuidado%20de%20la%20piel",
          "//kiero.co/categoria/barbería",
          "//kiero.co/categoria/manicure%20y%20pedicure"],
        "image_path": "//kiero.co/images/resources/Belleza20%y20%cuidado20%personal/","enable": [true]},
      "camaras y accesorios":  {"estructure":[1, 2, 3, 2],
        "links": ["","//kiero.co/categoria/Camaras",
          "//kiero.co/categoria/accesorios20%para20%cámaras",
          "//kiero.co/categoria/memorias%20digitales",
          "//kiero.co/categoria/bater%C3%ADas%20y%20cargadores",
          "//kiero.co/categoria/video",
          "//kiero.co/categoria/binoculares%20y%20telescopios",
          "//kiero.co/categoria/videoc%C3%A1maras"],
        "image_path": "//kiero.co/images/resources/camaras20%y20%accesorios/","enable": [true]},
      "celulares":{"estructure":[1, 2, 3, 2],
        "link": ["","//kiero.co/categoria/celulares",
          "//kiero.co/categoria/smartwatch",
          "//kiero.co/categoria/tel%C3%A9fonos",
          "//kiero.co/categoria/accesorios",
          "//kiero.co/categoria/Memorias%20para%20Celular",
          "//kiero.co/categoria/radios",
          "//kiero.co/categoria/estuches20%y20%fundas"],
        "image_path": "//kiero.co/images/resources/Celulares20%y20%telefonos/","enable": [true]},
      "consolas y videojuegos": {"estructure":[1, 2, 3, 2, 3, 2, 2],
        "links": ["","//kiero.co/categoria/playstation",
          "//kiero.co/categoria/xbox",
          "//kiero.co/categoria/atari",
          "//kiero.co/categoria/game%20boy",
          "//kiero.co/categoria/nvidia%20shield",
          "//kiero.co/categoria/Otros",
          "//kiero.co/categoria/sony%20psp",
          "//kiero.co/categoria/sega",
          "//kiero.co/categoria/playstation%20vita",
          "//kiero.co/categoria/GameCube  ",
          "//kiero.co/categoria/nintendo",
          "//kiero.co/categoria/mac",
          "//kiero.co/categoria/juegos",
          "//kiero.co/categoria/accesorios"],
        "image_path": "//kiero.co/images/resources/consolas20%y20%videojuegos/","enable": [true]},
      "electronica audio y video": {"estructure":[1, 2, 3, 2, 3, 2, 3, 2, 1],
        "links": ["","//kiero.co/categoria/audio%20para%20el%20hogar",
          "//kiero.co/categoria/audio%20profesional%20y%20djs",
          "//kiero.co/categoria/audio20%portátil",
          "//kiero.co/categoria/accesorios%20de%20audio%20y%20video",
          "//kiero.co/categoria/reproductores%20blu-ray",
          "//kiero.co/categoria/drones%20y%20accesorios",
          "//kiero.co/categoria/televisores",
          "//kiero.co/categoria/video%20beams%20y%20pantallas",
          "//kiero.co/busqueda/pilas,%20bater%C3%ADas%20y%20cargadores",
          "//kiero.co/categoria/Palms,%20Agendas%20y%20Accesorios",
          "//kiero.co/busqueda/reproductores%20mp3%20y%20mp4",
          "//kiero.co/categoria/ipod",
          "//kiero.co/categoria/lectores%20de%20libros%20digitales%20y%20accesorios",
          "//kiero.co/categoria/componentes%20electronicos",
          "//kiero.co/categoria/equipos%20de%20seguridad",
          "//kiero.co/categoria/dvd",
          "//kiero.co/categoria/calculadoras",
          "//kiero.co/categoria/gps"],
        "image_path": "//kiero.co/images/resources/electronica20%audio20%y20%video/","enable": [true]},
      "herramientas":{ "estructure":[1, 2, 3, 2],
        "links": ["","//kiero.co/categoria/construcci%C3%B3n",
          "//kiero.co/categoria/herramientas",
          "//kiero.co/categoria/herramientas%20manuales",
          "//kiero.co/categoria/herramientas%20el%C3%A9ctricas",
          "//kiero.co/categoria/Pisos,%20Paredes%20y%20Aberturas",
          "//kiero.co/categoria/mobiliario%20para%20cocinas",
          "//kiero.co/categoria/mobiliario%20para%20ba%C3%B1os"],
        "image_path": "//kiero.co/images/resources/herramientas20%y20%construccion","enable": [true]},
      "hogar": {"estructure":[1, 2, 3, 2, 1],
        "links": ["","//kiero.co/categoria/muebles",
          "//kiero.co/categoria/cocina%20y%20comedor",
          "//kiero.co/categoria/ba%C3%B1o",
          "//kiero.co/categoria/jardines%20y%20exteriores",
          "//kiero.co/categoria/muebles%20de%20acento",
          "//kiero.co/categoria/alcobas",
          "//kiero.co/categoria/decoracion%20del%20hogar",
          "//kiero.co/categoria/Artículos%20para%20el%20hogar"],
        "image_path": "//kiero.co/images/resources/hogar20%y20%muebles","enable": [true]},
      "industrias y oficinas": {"estructure":[1, 2, 3, 2],
        "links": ["","//kiero.co/categoria/equipamiento%20para%20oficinas",
          "//kiero.co/categoria/industria%20gastron%C3%B3mica",
          "//kiero.co/categoria/m%C3%A1quinas%20para%20industrias",
          "//kiero.co/categoria/Embalajes",
          "//kiero.co/categoria/equipo%20hidr%C3%A1ulico",
          "//kiero.co/categoria/industria%20textil",
          "//kiero.co/categoria/seguridad%20para%20industrias"],
        "image_path": "//kiero.co/images/resources/industrias20%y20%oficinas","enable": [true]},
      "instrumentos musicales": {"estructure":[1, 2, 3, 2],
        "links": ["", "//kiero.co/categoria/instrumentos%20de%20cuerda",
          "//kiero.co/categoria/instrumentos%20de%20viento",
          "//kiero.co/categoria/micr%C3%B3fonos",
          "//kiero.co/categoria/accesorios",
          "//kiero.co/categoria/amplificadores",
          "//kiero.co/categoria/bater%C3%ADas%20y%20percusi%C3%B3n",
          "//kiero.co/categoria/teclados%20y%20pianos"],
        "image_path": "//kiero.co/images/resources/instrumentos20%musicales","enable": [true]},
      "juegos y juguetes": {"estructure":[1, 2, 3, 2, 3, 2, 3, 2, 3, 3],
        "links": ["", "//kiero.co/categoria/disfraces%20y%20juegos%20de%20fantas%C3%ADa",
          "//kiero.co/categoria/peluches",
          "//kiero.co/categoria/Juguetes%20y%20Carros%20de%20Control%20Remoto",
          "//kiero.co/categoria/electr%C3%B3nica%20para%20ni%C3%B1os",
          "//kiero.co/categoria/juegos%20al%20aire%20libre",
          "//kiero.co/categoria/arte%20y%20manualidades",
          "//kiero.co/categoria/Juguetes20%de20%construcción",
          "//kiero.co/categoria/aprendizaje%20y%20educaci%C3%B3n",
          "//kiero.co/categoria/articulos%20para%20fiestas",
          "//kiero.co/categoria/juguetes%20montables",
          "//kiero.co/categoria/juegos%20de%20imitaci%C3%B3n",
          "//kiero.co/categoria/juegos%20estrat%C3%A9gicos",
          "//kiero.co/categoria/Juegos%20de%20Adultos",
          "//kiero.co/categoria/Juguetes%20de%20Novedad",
          "//kiero.co/categoria/mu%C3%B1ecas",
          "//kiero.co/categoria/Juguetes20%para20%Bebes20%y20%Niños",
          "//kiero.co/categoria/rompecabezas",
          "//kiero.co/categoria/figuras%20de%20acci%C3%B3n%20y%20estatuas",
          "//kiero.co/categoria/juegos%20y%20veh%C3%ADculos",
          "//kiero.co/categoria/hobbies",
          "//kiero.co/categoria/titeres",
          "//kiero.co/categoria/mochilas20%y20%loncheras20%(validar)",
          "//kiero.co/categoria/pasatiempos"],
        "image_path": "//kiero.co/images/resources/juegos20%y20%juguetes","enable": [true]},
      "relojes y joyas": {"estructure":[1, 3, 2, 3, 2, 3, 1],
        "links": ["","//kiero.co/categoria/relojes%20de%20pulsera",
          "//kiero.co/categoria/relojeras",
          "//kiero.co/categoria/Accesorios%20Para%20Relojes",
          "//kiero.co/categoria/joyeria",
          "//kiero.co/categoria/smartwatch",
          "//kiero.co/categoria/relojes%20digitales",
          "//kiero.co/categoria/relojes%20de%20bolsillo",
          "//kiero.co/categoria/Relojes%20Cuarzo",
          "//kiero.co/categoria/relojes%20deportivos",
          "//kiero.co/categoria/relojes%20de%20cuero",
          "//kiero.co/categoria/relojes%20casuales",
          "//kiero.co/categoria/relojes%20de%20acero%20inoxidable",
          "//kiero.co/categoria/relojes%20analogicos",
          "//kiero.co/categoria/marcas"],
        "image_path": "//kiero.co/images/resources/relojes20%y20%joyas","enable": [true]},
      "ropa zapatos y accesorios": {"estructure":[1, 2, 2],
        "links": ["","//kiero.co/categoria/ropa%20y%20accesorios%20para%20ni%C3%B1os",
          "//kiero.co/categoria/ropa%20y%20accesorios%20para%20ni%C3%B1as",
          "//kiero.co/categoria/ropa%20y%20accesorios%20para%20mujeres",
          "//kiero.co/categoria/ropa%20y%20accesorios%20para%20hombres"],
        "image_path": "//kiero.co/images/resources/ropa,zapatos20%y20%accesorios","enable": [true]},
      "vehiculos y accesorios": {
        "estructure": [1, 2, 3, 2, 3, 2], "links": ["//kiero.co/categoria/Repuestos%20para%20Carro",
          "//kiero.co/categoria/audio%20para%20carro",
          "//kiero.co/categoria/accesorios%20para%20aviones",
          "//kiero.co/categoria/Afinación%20y%20Rendimiento%20para%20Carro",
          "//kiero.co/categoria/accesorios%20para%20carro",
          "//kiero.co/categoria/herramientas%20para%20carro",
          "//kiero.co/categoria/Repuestos%20para%20Carro",
          "//kiero.co/categoria/accesorios%20de%20exterior%20para%20carro",
          "//kiero.co/categoria/accesorios%20de%20interior%20para%20carro",
          "//kiero.co/categoria/accesorios%20para%20moto",
          "//kiero.co/categoria/llantas", "//kiero.co/categoria/Repuestos%20para%20Moto"],
        "image_path": "//kiero.co/images/resources/vehiculos20%y20%accesorios","enable": [true]}
    }

    return (
      <div className="container category-list">
        <Nav user={u_data.user} home={true} authenticated={u_data.authenticated} />
        <section className="content">
          <img className="banner-principal" src={urlBanner} />
          <Finding />
          <Tickets />
          <Finding />
          <Tickets />
          <Finding />
        </section>
        <Footer />
        <div className="footer-social">
          <Link href={url}><a target="_blank"><img src={Logo1} /></a></Link>
          <Link href={url}><a target="_blank"><img src={Logo2} /></a></Link>
        </div>
      </div>
    );
  }
}
